### ISSUE TITLE
Hide Secret data in Object status

### ISSUE THREAD

**Issue by lsviben** [crossplane-contrib/provider-kubernetes#178]
### What problem are you facing?

When the K8s resource being managed is a K8s Secret resource, we could consider sanitizing/redacting the Secret.Data fields in status.AtProvider to prevent leaking out/exposing Secret data. Shuttling data from managed Secret resources can already use `spec.references[].patchesFrom` or `spec.connectionDetails` without needing to rely on `status.AtProvider` fields for patching. 

Note that this would really matter only for Observed Secrets, as for Secrets that are created by the provider, the data is already exposed at `spec.forProvider.manifest`.

### How could Crossplane help solve your problem?

To avoid breaking existing setups which are relying on patching from the status, we could add an option `spec.sensitiveDataPolicy: Hide (Show)` (preffered) or `spec.secretDataInStatus: false/true` .

By default the data would be redacted so it would still require a change for existing setups, although a minor one.

**Comment by lsviben** [comment]
> The required change may be minor but the impact of not making the change is still breaking, so I think the default should be the existing behavior for at least one release before changing to the desired value, 2 or 3 releases would be preferable. That would give users enough time to make the changes and test before getting hit with the modified default.

Ok, makes sense to keep the old behavior as default for now to avoid breaking current setups.

**Comment by ravilr** [comment]
> To avoid breaking existing setups which are relying on patching from the status, we could add an option spec.sensitiveDataPolicy: Hide (Show) (preffered) or spec.secretDataInStatus: false/true .

Another option to keep things simple, the new behavior of redacting Secret.Data (if Object being managed is a K8s Secret) could be controlled by an arg/flag in the provider-kubernetes itself,  instead of per Object spec schema field ?  If the flag is turned on the provider deployment args, then any secret.Data would be replaced with `redacted: nil` in status.atProvider.manifest across all Objects.

**Comment by bobh66** [comment]
I can see where this makes sense for observed secrets that the provider does not already have the sensitive data for, but in cases where the provider is creating the secret, the sensitive data is exposed in the `forProvider.manifest` of the `Object` anyway.  That's not an excuse to not implement the feature, but users need to understand the limitations.

**Comment by lsviben** [comment]
> > To avoid breaking existing setups which are relying on patching from the status, we could add an option spec.sensitiveDataPolicy: Hide (Show) (preffered) or spec.secretDataInStatus: false/true .
> 
> Another option to keep things simple, the new behavior of redacting Secret.Data (if Object being managed is a K8s Secret) could be controlled by an arg/flag in the provider-kubernetes itself, instead of per Object spec schema field ? If the flag is turned on in the provider deployment args, then any secret.Data would be replaced with `redacted: nil` in status.atProvider.manifest across all Objects(which are managing K8s Secrets).

Good idea! I wonder if there is an use case where users would want to have a mix (some redacted, some dont). But it seems like an edge case that could be solved differently, by getting the status.atProvider data in the same way across their env.

> I can see where this makes sense for observed secrets that the provider does not already have the sensitive data for, but in cases where the provider is creating the secret, the sensitive data is exposed in the forProvider.manifest of the Object anyway. That's not an excuse to not implement the feature, but users need to understand the limitations.

True, Ill update the description to make it clear. And we should keep it in mind when describing the feature.

**Comment by bobh66** [comment]
I think in all cases the `status.atProvider.manifest.data` content needs to be available to the composition engine for patching, otherwise there isn't much point in observing the secret in the first place.  I'm not sure how we sanitize the data and still make it available for use by the composition engine.

**Comment by ravilr** [comment]
> I think in all cases the `status.atProvider.manifest.data` content needs to be available to the composition engine for patching, otherwise there isn't much point in observing the secret in the first place. I'm not sure how we sanitize the data and still make it available for use by the composition engine.

Not necessarily. In cases where provider-kubernetes's Object usages are limited to shuttling observed secret data to/from remote<->control-plane clusters, Compositions can leverage Object's `spec.references[].patchesFrom` or `spec.connectionDetails` to achieve that without needing to rely on Observed secret data being available under Object status.
