### ISSUE TITLE
observe failed: cannot get object: no matches for kind "Namespace" in         version "v1"

### ISSUE THREAD

**Issue by bitgandtter** [crossplane-contrib/provider-kubernetes#23]
### What happened?
i tried to create a namespace on a k8s cluster and got following message 

observe failed: cannot get object: no matches for kind "Namespace" in version "v1"

### How can we reproduce it?
mu current steps are

1. spin a new gke cluster
2. install crossplane and this providers
3. use crossplane to create a second gke cluster
4. use this provider to try to create a namespace on the second cluster

### What environment did it happen in?
Crossplane version: 1.6.x

* Cloud provider or hardware configuration: gcloud dke
* Kubernetes version (use `kubectl version`) 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-17T02:23:27Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3-gke.700", GitCommit:"e21de5d6cf1b351bc99285c3c762098b8617b773", GitTreeState:"clean", BuildDate:"2021-11-05T09:25:32Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes distribution GKE

**Comment by haarchri** [comment]
Think you need to set for GCP 

https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/provider/config.yaml#L21
then the access is working

**Comment by bitgandtter** [comment]
Yes in fact the doc should specify that in case of gke the identity needs to be specified. Closing it now
