### ISSUE TITLE
Possibility to patch object from yaml file

### ISSUE THREAD

**Issue by braghettos** [crossplane-contrib/provider-kubernetes#40]
### What problem are you facing?

I would like to install an operator with provider-kubernetes but the yaml is too long and complex to copy+paste it. This raw yaml file is available online on GitHub. 

### How could Crossplane help solve your problem?

It would be great if provider-kubernetes could allow patching from online yaml files.

**Comment by bobh66** [comment]
Is this the same as https://github.com/crossplane-contrib/provider-kubernetes/issues/33 ?

**Comment by braghettos** [comment]
Actually it is! I will close this one, thanks @bobh66
